### ISSUE TITLE
[BUG] tf.gradients is not supported when eager execution

### ISSUE THREAD

**Issue by ebudemir** [albermax/innvestigate#320] opened 2023-09-28 20:32 UTC
Hello I got the following exception 

Traceback (most recent call last):
  File "xai.py", line 274, in <module>
    a = analyzer.analyze(data)
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/network_base.py", line 250, in analyze
    self.create_analyzer_model()
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/network_base.py", line 164, in create_analyzer_model
    tmp = self._create_analysis(
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/deeptaylor.py", line 133, in _create_analysis
    return super()._create_analysis(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/reverse_base.py", line 268, in _create_analysis
    reversed_input_tensors, reversed_tensors = self._reverse_model(
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/reverse_base.py", line 242, in _reverse_model
    return igraph.reverse_model(
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/backend/graph.py", line 1253, in reverse_model
    reversed_Xs = reverse_mapping(
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/reverse_base.py", line 122, in _gradient_reverse_mapping
    grad = ibackend.gradients(Xs, Ys, reversed_Ys)
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/backend/__init__.py", line 82, in gradients
    grad = tf.gradients(Ys, Xs, grad_ys=known_Ys, stop_gradients=Xs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gradients_impl.py", line 311, in gradients_v2
    return gradients_util._GradientsHelper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gradients_util.py", line 476, in _GradientsHelper
    raise RuntimeError("tf.gradients is not supported when eager execution "
RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

I have added 
tf.compat.v1.disable_eager_execution()

to my code after some google search. Then, I got another exception. It is going weird.

Traceback (most recent call last):
  File "xai.py", line 274, in <module>
    a = analyzer.analyze(data)
  File "/usr/local/lib/python3.8/dist-packages/innvestigate/analyzer/network_base.py", line 274, in analyze
    ret = self._analyzer_model.predict_on_batch(X)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/engine/training_v1.py", line 1321, in predict_on_batch
    outputs = self.predict_function(inputs)
  File "/usr/local/lib/python3.8/dist-packages/keras/src/backend.py", line 4609, in __call__
    fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/session.py", line 1482, in __call__
    ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) FAILED_PRECONDITION: Could not find variable denselc/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/denselc/kernel/N10tensorflow3VarE does not exist.
         [[{{node denselc/MatMul/Identity/ReadVariableOp}}]]
         [[Func/gradients_2/dropout_2/cond_grad/StatelessIf/then/_60/input/_232/_151]]
  (1) FAILED_PRECONDITION: Could not find variable denselc/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Resource localhost/denselc/kernel/N10tensorflow3VarE does not exist.
         [[{{node denselc/MatMul/Identity/ReadVariableOp}}]]

___

I was just using innvestigate to my previously created model files (.h5). I tested deep taylor and guided_backprop and faced the same issue. I do not know how to proceed.

### Platform information
 OS: docker NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
Python version: [3.8]
innvestigate                 2.1.1
tensorflow                   2.13.0

**Comment by adrhill** [comment] 2023-10-04 16:34
Closing this since it is a duplicate of https://github.com/albermax/innvestigate/issues/285.

**Closed by adrhill** 2023-10-04 16:34 UTC
Labels: triage
